### ISSUE TITLE
buildDial() virtual methods in DialBase

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#285]
Is it absolutly necessary that we predefine those `buildDial` virtual methods?

With this I understand we don't need to recast to the derived class in order to call the specific instance. However, I think `buildDial()` itself makes no sense in `DialBase` as it introduces unused dependencies (like `#include "TGraph.h"`). Also this means each new derivative would required to add a specific instance of the virtual method.

Wouldn't it be better to actually cast back to the derived class within the dial factories and use specific setters and `buildDial` method instead?

https://github.com/gundam-organization/gundam/blob/e249ff5d659b437933d946be638d5b435744fe2a/src/DialDictionary/DialDefinitions/include/DialBase.h#L52-L69

**Comment by ClarkMcGrew** [comment]
You ask if it is "absolutely necessary", and, of course it isn't, but the question is setting up a tautology.  Down-casts are usually "needed" to work around a mistake, so there needs to be a compelling reason to force their use.  In fact, we have compelling reasons to avoid using down-casts.

The current DialBase API has warts to minimize the changes in other parts of the code, but the fundamental design principle is that derived classes specialize behavior.  That, in turn, makes the project more maintainable since the API is explicitly saying the types of input it will accept, and how the derived DialBase object will respond to unexpected kinds of data (i.e. for now, brutally, with a runtime_error).  

In the "USE_NEW_DIALS" implementation there are a small number of de facto DialBase invariants (that still need to be documented).  

1) There is a single return value (i.e. weight) from one or more input parameters (realized by evalResponse)
2) There are internal data describing the evalResponse calculation, and they must be exposed (e.g. for GPU). (realized by getDialData)
3) There are a finite number of kinds of initialization data, primarily from ROOT (e.g. TGraph, TSpline3, &c).  The list of kinds of data will grow, but will always be limited (realized by buildDial). 

These invariants are captured in the API.  And, since the API should not make assumptions about how the dial base objects will be managed (i.e. it shouldn't assume a factory pattern), that means that the different types of inputs need to be listed.

As far as the specific class signatures, my preference would have been to follow the root convention of pointers (e.g. "TGraph*" "TSpline3*") and have forward-decls in the DialBase header file.  But, that didn't match the coding style where the DialBase objects are used [1], and since we are completely dependent on ROOT, adding the extra "TGraph.h" and "TSpline.h" files to the compilation seemed the best compromise.

[1] The usage (e.g. in DialDictionary and DatasetManager) seemed to favor using references, and not pointers for the initialization data.

**Comment by nadrino** [comment]
I see. But why in that case we can't use a custom constructor that would directly take the relevant input to effectivly "buildDial"?

Otherwise one of the original implementation I came up with, was the use of multiple layers of virtualization. I understood this is not optimal for the keeping of several vtables overhead.

However, could we create a virtualised layer dedicated to the `buildDial()` related to the DialFactory? For example the`SplineDialBaseFactory` would return a `DialBase` ptr while effectivly creating a `SplineBase` (inheriting from a DialBase) handling the buildDial.

In the future, I'd like to extend the DialBase derivative to a wider range and `TGraph` or `TSpline3` initializers would be specific cases. But yeah, for the moment I don't see the use of this design (that will probably make much more sense in the GPU part!)

**Comment by ClarkMcGrew** [comment]
> I see. But why in that case we can't use a custom constructor that would directly take the relevant input to effectivly "buildDial"?

That particular idiom often has a couple of undesirable consequences.  First, using it means DialBase has as many constructors as we would have "buildDial" methods, (so no win there), or it means that the acceptable methods of initialization are hidden inside derived classes (misses one of the desiderata above).  Second it has a tendency to produce large "if-block" statements since implementation choice and initialization are not cleanly separated.  Third, using a custom constructor idiom tends to force the constructor to throw an exception when something "goes wrong" during consistency checks, and it makes the tear-down behavior more complicated (when the object is partially constructed). 

> However, could we create a virtualised layer dedicated to the `buildDial()` related to the DialFactory? For example the`SplineDialBaseFactory` would return a `DialBase` ptr while effectivly creating a `SplineBase` (inheriting from a DialBase) handling the buildDial.

It sounds like you are equating a factory like DialBaseFactory with a "DialBase" constructor, but those are logically different operations.  Essentially: 1) The factory interprets the user input and chooses the correct behavior; 2) and, the dial base object implements the behavior.  The "Graph"/"Spline" in the names of the different factories refers to the type of user input being handled, not the type of the object being created.  

For your specific example, the SplineDialBaseFactory might not return a dial with a spline.  

> In the future, I'd like to extend the DialBase derivative to a wider range and `TGraph` or `TSpline3` initializers would be specific cases. 

This is part of the argument for using the buildDial idiom, so I do not understand what you are saying here.  The current set of buildDial overloads are based on what is being used in gundam, not an exhaustive list of everything needed in the future.  Check out the invariants.  The key for the third invariant is that there are not a lot of ways we will want to initialize a dial base derived object, but more methods are expected in the future.

**Comment by nadrino** [comment]
> It sounds like you are equating a factory like DialBaseFactory with a "DialBase" constructor, but those are logically different operations. Essentially: 1) The factory interprets the user input and chooses the correct behavior; 2) and, the dial base object implements the behavior. The "Graph"/"Spline" in the names of the different factories refers to the type of user input being handled, not the type of the object being created.
>
> For your specific example, the SplineDialBaseFactory might not return a dial with a spline.

Sure, I mean the factory is here to initialize the correct dial. Afterward no downcast is necessary. However during the initialization, it's precisely where we would expect to fill up the data with the downcasted types.

My point concern here is that the `buildDial()` virtual methods don't make sense as long as the Dial derivatives are not defined. Typically when I read `DialBase` header, I don't understand these overloaded `buildDial()` methods until I come across the meaningful derivatives. I mean it would have been OK if the arguments were similar in each case, but here we need to specify the type and amount of inputs already in `DialBase`. 

To sum up, I don't see the reason why `buildDial` is made to be general but in fact it is specific to the initialization. In the future, I fear it's going to be a complicated to implement other dials from higher levels. As an example: "Let's call this `buildDial(v1,v2,v3)` for this specific `XxxDial`, but wait it is actually not implemented for this one."

For instance in the `SplineDialBaseFactory`, instead of working with a `DialBase` all the way through we could use the relevant derivative as long as the object isn't initialized yet:

```c++
DialBase* dialBase{nullptr};
// ...
if( useCachedDial_ ){
  std::unique_ptr<UniformSplineCache> dialInitializer = std::make_unique<UniformSplineCache>();
  dialInitializer.buildDial( ... );
  dialBase = dialInitializer.release();
}
return dialBase;
```

Here `buildDial` could be defined within `UniformSpline` declaration. We have several options there:
- Only implement the specific non-virtual `buildDial(x,x,x)` method
- Implement the specific `buildDial(x,x,x) override` in `UniformSpline` while it is virtualized either in an intermediate layer: `class SplineDial : public DialBase` or within another template class as you've done for the `Cache` derived class. This way we could call `buildDial(x,x,x)` once as it is currently done.

But may be I missed something you need for the GPU implementation

**Comment by ClarkMcGrew** [comment]
Interface has stablized, so closing this.
