### ISSUE TITLE
Removing deprecated old Dial class

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#309]
As the dial classes are now handled separatly from the ParameterSet lib, we could safelty remove the old implementation.

This would imply to remove all the `USE_NEW_DIALS` checks along with the code

**Comment by nadrino** [comment]
@ClarkMcGrew I added you to the assignees, but it is just to check if you still need those while upgrading the CacheManager!

**Comment by ClarkMcGrew** [comment]
Also,  1.7.0 is basically ready to go out the door as soon as we get sign off from Lena and Vlada that it's not crazy wrong.  Since this is an enhancement, I'd suggest waiting for either the next release, or not putting it in a milestone.  I don't think we should be making this sort of larger change for 1.7.0 (but remove the USE_NEW_DIAL defs from CMakeLists.txt)

**Comment by nadrino** [comment]
Ok I'm tagging this as 1.7.1 milestone then!

**Comment by ClarkMcGrew** [comment]
We can restart this as soon as the new Cache::Manager code is checked out with OA2022.  It's basically working with OA2024, so that shouldn't be a problem.

**Comment by ClarkMcGrew** [comment]
Cache::Manager is good to go now, so I think we can remove the old dial code.  If I don't hear otherwise (and @nadrino doesn't do it first), I'll try to do this next week.
