### ISSUE TITLE
Bug with CompactSpline eval

### ISSUE THREAD

**Issue by nadrino** [gundam-organization/gundam#315]
I've made a few tests and printouts to splot where the evaluation is failing when using CompactSplines. Here is the printout.

It seems that the code is looking for the element of the input array `data[4]` while its size is only 4. 

@ClarkMcGrew I don't understand very well all these numbers, do you know what are they supposed to do?

```
13/05/2023 15:34:24 [EventDialCache]: Invalid dial response:
13/05/2023 15:34:24 [CompactSpline]: d43 = -nan
13/05/2023 15:34:24 [CompactSpline]: data[2+d43_1] = -nan
13/05/2023 15:34:24 [CompactSpline]: dim = 4
13/05/2023 15:34:24 [CompactSpline]: d43_1 = 2
13/05/2023 15:34:24 [CompactSpline]: d43_0+1 = 2
13/05/2023 15:34:24 [CompactSpline]: ix+1 = 1
13/05/2023 15:34:24 [EventDialCache]: CompactSpline: input({ Cross-Section Systematics/#57_MPi_Multi_Shape=0 }) supervisor(minResponse=0, maxResponse=100) response=-nan
13/05/2023 15:34:24 [EventDialCache]: CompactSpline: spline data = { 0, 1, 1, 1.667 }
13/05/2023 15:34:24 [EventDialCache]: CompactSpline: defined bounds = { 0, 1 }
13/05/2023 15:34:24 [EventDialCache]: CompactSpline: allow extrapolation ? 1
13/05/2023 15:34:24 [EventDialCache]: CompactSpline: EVAL MANUAL at 0:-nan
```

**Comment by ClarkMcGrew** [comment]
Thanks for finding that.  I can't tackle this right now since I'm heading out, but I know where it's coming from.  This is Compact, not Monotonic, right?  It's almost the same code, but if the bug is in one, it's probably in both.

**Comment by nadrino** [comment]
Great! Yeah is from the `CalculateCompactSpline` header

**Comment by ClarkMcGrew** [comment]
Didn't have a chance to fix things, but a quick glance at the usage I see that `dim` is suppose to be the number of points, not the size of the array (90% confidence until I look more carefully).   For the example above, dim should be 2 (not 4).  I'll verify and get a pull request for CompactSpline (and check the other spline codes) too.

**Comment by nadrino** [comment]
Ah! Interesting, indeed what is passed to the function is directly the size of the array

<img width="908" alt="Screenshot 2023-05-13 at 20 28 32" src="https://github.com/gundam-organization/gundam/assets/17473586/57113e94-30a4-47c4-b830-0c03d1a1bd62">

**Comment by nadrino** [comment]
It's actually called like that for every `Calculate*Spline`

<img width="1094" alt="Screenshot 2023-05-13 at 20 32 02" src="https://github.com/gundam-organization/gundam/assets/17473586/d615db44-65c6-4b51-9efa-176db0006f4e">

**Comment by nadrino** [comment]
Also I'm confused why a two point graph would described by a CompactSpline... I mean the only shape we can describe out of only two point is a straight line!

**Comment by ClarkMcGrew** [comment]
Let's just say the interface is not uniform and leave it at that!  CalculateGeneralSpline and CalculateUniformSpline take the array size.  CalculateCompactSpline and CalculateMonotonicSpline take the number of knots.  

I'm going to fix this in two stages.  First, is to fix the current DialDefinition/CompactSpline so that it uses the current interface (same for Monotonic).   Later, I think it's worth making the different Caculate*Spline routines have a more uniform interface.

**Comment by nadrino** [comment]
Great! Thank you very much Clark!

**Comment by nadrino** [comment]
https://github.com/gundam-organization/gundam/blob/f22504fc8f08cc09ec93314409d6f451600cc9d6/src/DialDictionary/DialFactories/src/SplineDialBaseFactory.cpp#L242

I did this implementation to convert 2 points graphs into a polynomial dial. Do you think it would make sense in the main branch?

**Comment by ClarkMcGrew** [comment]
No, I really don't, for a few of reasons.  Using the polynomial to the spline factory adds new complexity without adding new functionality.  Using a C-R spline minimizes the number of concepts in that part of the code (and, using the polynomial replaces one line with several in the factory).   The catmull-rom spline is computationally fairly simple.  Last I looked, the polynomial still needed to be finished since it couldn't turn off extrapolation.  The polynomial isn't implemented for GPU [also, from a quick look at the code, I think you used a+b*x+c*x*x +... which isn't stable, so before Polynomial hits production, we should change to the more stable a+(b+(c+d*x)*x)*x) form.  As far as I know, this would be the only place that it's used and it hasn't been requested as a feature for any T2K analysis.  A two point C-R is equivalent to the two point form of a line, but if it's too heavy, then I'd suggest replacing it with a "uniform" graph implementation before moving to a polynomial.

After writing it out, I actually think it would be a bad idea to use Polynomial.

**Comment by nadrino** [comment]
I see, however the calculation is actually done that way you described: `a+(b+(c+dx)*x)*x)`. I mean it's a trivial dial that does not require much maintaining and would be very fast to evaluate as it only requires a few variable to declare while evaluating. 

<img width="518" alt="Screenshot 2023-05-14 at 13 21 22" src="https://github.com/gundam-organization/gundam/assets/17473586/08c91888-28e5-4f75-9016-ed54f7780ddf">

If you don't feel confortable with it in the Spline factory I can only leave it for explicit user definitions. I think it might be very useful in the future to propagate specific systematics
